Repository Taka1304/ds-lms-demo, pull requests merged in 2025-04, with the labels that each got.

#79 #67 #68 ユーザー関連API実装
  src/app/api/[[...route]]/route.ts
  src/app/api/[[...route]]/users/getUser.ts
  src/app/api/[[...route]]/users/index.ts
  src/app/api/[[...route]]/users/updateUser.ts
Labels: feature ✨, backend :zap:

#80 ライト，ダークモードの実装，テーマカラーの変更機能の実装
  bun.lockb
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/components/layout/sidebar/index.tsx
  src/components/layout/sidebar/theme-selector.tsx
  src/components/layout/sidebar/theme-switcher.tsx
  src/components/layout/theme-provider.tsx
  src/components/ui/button.tsx
Labels: feature ✨, frontend :globe_with_meridians:

#82 設定、コメント追記等
  .vscode/settings.json
  src/app/api/[[...route]]/middleware/auth.ts
Labels: refactor :recycle:

#85 feat: not-found.tsxとerror.tsxの追加
  src/app/error.tsx
  src/app/not-found.tsx
  src/app/students/page.tsx
Labels: feature ✨, frontend :globe_with_meridians:

#81 #53 管理者用サイドバーの実装
  biome.json
  bun.lockb
  package.json
  src/app/manage/template.tsx
  src/components/layout/sidebar/const.ts
  src/components/layout/sidebar/index.tsx
  src/components/layout/sidebar/nav.tsx
  src/components/layout/sidebar/theme-switcher.tsx
  src/components/ui/badge.tsx
  src/components/ui/sidebar.tsx
Labels: feature ✨, frontend :globe_with_meridians:

#96 #95 updateSubmissionの実装
  prisma/migrations/20250419084700_fix_submission/migration.sql
  prisma/schema.prisma
  src/app/api/[[...route]]/courses/problems/index.ts
  src/app/api/[[...route]]/courses/problems/updateSubmission.ts
Labels: feature ✨, backend :zap:

#99 #97 デフォルトの入力値を反映させる
  prisma/migrations/20250419143809_default_code/migration.sql
  prisma/schema.prisma
  src/app/students/courses/[courseId]/[problemId]/page.tsx
  src/features/problems/components/programming-interface.tsx
Labels: feature ✨

#102 #101 複数行入力への対応
  src/features/problems/components/python-execution-provider.tsx
Labels: bug 🐛, high priority :fire:, frontend :globe_with_meridians:

#107 #75 問題提出・評価ページ及びロジックの実装
  bun.lockb
  package.json
  src/app/api/[[...route]]/courses/problems/getSubmission.ts
  src/app/api/[[...route]]/courses/problems/index.ts
  src/app/api/[[...route]]/courses/problems/updateSubmission.ts
  src/app/layout.tsx
  src/app/students/courses/[courseId]/[problemId]/[submissionId]/page.tsx
  src/components/ui/editor.tsx
  src/components/ui/sidebar.tsx
  src/components/ui/sonner.tsx
  src/features/problems/components/console-view.tsx
  src/features/problems/components/evaluation-result.tsx
  src/features/problems/components/programming-interface.tsx
  src/features/problems/components/python-execution-provider.tsx
  src/features/problems/components/test-result-item.tsx
  src/features/problems/types/index.ts
Labels: bug 🐛, feature ✨, high priority :fire:, frontend :globe_with_meridians:, backend :zap:
