Repository Taka1304/ds-lms-demo, pull requests merged in 2025-07, with the labels that each got.

#181 issue178 : Answerテーブルを追加
  prisma/migrations/20250703021617_add_answer/migration.sql
  prisma/schema.prisma
Labels: db_migration :warning:

#185 Feat✨: ConsoleをResizableにする
  src/features/problems/components/console-view.tsx
  src/features/problems/components/programming-interface.tsx
Labels: feature ✨, frontend :globe_with_meridians:

#184 #166 TailwindCSS v4 対応
  bun.lockb
  package.json
  postcss.config.mjs
  src/app/auth/signin/page.tsx
  src/app/globals.css
  src/app/manage/courses/[courseId]/[problemId]/page.tsx
  src/app/manage/courses/new/page.tsx
  src/app/manage/courses/page.tsx
  src/app/students/courses/[courseId]/[problemId]/page.tsx
  src/components/layout/sidebar/nav.tsx
  src/components/layout/sidebar/user.tsx
  src/components/ui/alert.tsx
  src/components/ui/aspect-ratio.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/breadcrumb.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/card.tsx
  src/components/ui/carousel.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/collapsible.tsx
  src/components/ui/dialog.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/nav-guard-dialog.tsx
  src/components/ui/pagination.tsx
  src/components/ui/popover.tsx
  src/components/ui/progress.tsx
  src/components/ui/resizable.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/select.tsx
  src/components/ui/separator.tsx
  src/components/ui/sheet.tsx
  src/components/ui/sidebar.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/sonner.tsx
  src/components/ui/switch.tsx
  src/components/ui/table.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/tooltip.tsx
  src/features/courses/[courseId]/components/card-content.tsx
  src/features/landing/cta.tsx
  src/features/landing/hero.tsx
  src/features/maintenance/index.tsx
  src/features/manage/problem/components/index.tsx
  src/hooks/use-mobile.ts
  src/hooks/use-mobile.tsx
  tailwind.config.ts
Labels: frontend :globe_with_meridians:, refactor :recycle:

#180 Issue/133: 問題文をコピーした際に、特定のプロンプトを忍び込ませる機能追加
  src/app/manage/courses/[courseId]/[problemId]/page.tsx
  src/app/manage/courses/new/page.tsx
  src/app/manage/courses/page.tsx
  src/features/problems/components/programming-interface.tsx
Labels: frontend :globe_with_meridians:
