Repository Taka1304/ds-lms-demo, pull requests merged in 2025-05, with the labels that each got.

#113 Umamiが動作していない不具合の修正
  src/app/error.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
Labels: bug 🐛, refactor :recycle:

#115 #104 管理者用 問題作成ページの実装
  bun.lockb
  lefthook.yml
  package.json
  prisma/migrations/20250506142708_drop_slug/migration.sql
  prisma/schema.prisma
  src/app/api/[[...route]]/courses/problems/createProblem.ts
  src/app/api/[[...route]]/courses/problems/index.ts
  src/app/api/[[...route]]/courses/problems/updateProblem.ts
  src/app/contact/layout.tsx
  src/app/manage/courses/[courseId]/[problemId]/debug/page.tsx
  src/app/manage/courses/[courseId]/[problemId]/edit/page.tsx
  src/app/manage/courses/[courseId]/new/page.tsx
  src/app/students/courses/[courseId]/[problemId]/page.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/form.tsx
  src/components/ui/label.tsx
  src/components/ui/switch.tsx
  src/features/manage/problem/components/index.tsx
  src/features/manage/problem/types/schema.ts
  src/features/problems/components/action-bar.tsx
  src/features/problems/components/programming-interface.tsx
  src/features/problems/components/python-execution-provider.tsx
Labels: bug 🐛, feature ✨, frontend :globe_with_meridians:, backend :zap:

#121 #117 コース一覧改修 + UserProgress周りのロジック追加
  src/app/api/[[...route]]/courses/getCourseList.ts
  src/app/api/[[...route]]/courses/problems/updateSubmission.ts
  src/app/students/courses/page.tsx
  src/components/layout/header.tsx
  src/components/ui/progress.tsx
  src/features/courses/components/CoursesCarousel.stories.tsx
  src/features/courses/components/CoursesCarousel.tsx
  src/features/courses/components/CoursesCarouselCard.tsx
  src/features/courses/components/Pagination.tsx
Labels: bug 🐛, feature ✨, high priority :fire:, frontend :globe_with_meridians:, backend :zap:, refactor :recycle:

#110 #55 プライバシーポリシーページの作成
  src/app/privacy/page.tsx
Labels: feature ✨, frontend :globe_with_meridians:

#127 #77 TLE発生時に再実行できないバグを修正
  src/app/auth/signin/page.tsx
  src/features/problems/components/programming-interface.tsx
  src/features/problems/components/python-execution-provider.tsx
Labels: feature ✨, frontend :globe_with_meridians:, easy :beginner:

#132 Refactor: feat/432
  src/features/problems/components/programming-interface.tsx
Labels: feature ✨, frontend :globe_with_meridians:

#130 feat/432
  .vscode/settings.json
  src/features/problems/components/programming-interface.tsx
Labels: feature ✨, frontend :globe_with_meridians:, easy :beginner:

#128 feat:プロフィール設定機能追加
  bun.lockb
  package.json
  prisma/migrations/20250509154740_add_user_group/migration.sql
  prisma/schema.prisma
  src/app/api/[[...route]]/users/index.ts
  src/app/api/[[...route]]/users/updateUser.ts
  src/app/profile/page.tsx
  src/app/profile/template.tsx
  src/features/profile/index.tsx
Labels: feature ✨, high priority :fire:

#136 #100 離脱防止ダイアログの実装
  bun.lockb
  package.json
  src/app/api/[[...route]]/courses/problems/submitProblem.ts
  src/app/layout.tsx
  src/components/ui/nav-guard-dialog.tsx
  src/features/problems/components/programming-interface.tsx
Labels: feature ✨, frontend :globe_with_meridians:

#146 認証でOAuthAccountNotLinkedが発生するのを修正
  prisma/migrations/20250526111148_ext_expires_in/migration.sql
  prisma/schema.prisma
Labels: bug 🐛, backend :zap:, db_migration :warning:

#148 Fix🐛: UserProgressが0の場合に対処
  src/app/students/courses/[courseId]/page.tsx
Labels: bug 🐛

#149 #106 ユーザー用ダッシュボードの仮実装
  bun.lockb
  package.json
  src/app/api/[[...route]]/dashboard/activityHeatmap.ts
  src/app/api/[[...route]]/dashboard/index.ts
  src/app/api/[[...route]]/route.ts
  src/app/api/[[...route]]/submission/getSubmission.ts
  src/app/api/[[...route]]/submission/getSubmissionList.ts
  src/app/api/[[...route]]/submission/index.ts
  src/app/api/[[...route]]/submission/updateSubmission.ts
  src/app/layout.tsx
  src/app/students/courses/[courseId]/[problemId]/[submissionId]/page.tsx
  src/app/students/page.tsx
  src/components/layout/sidebar/index.tsx
  src/components/ui/calendar.tsx
  src/components/ui/date-range-picker.tsx
  src/components/ui/popover.tsx
  src/features/courses/[courseId]/components/card-content.tsx
  src/features/courses/components/CoursesCarouselCard.tsx
  src/features/dashboard/activity-heatmap.tsx
  src/features/dashboard/container/activity-heatmap.tsx
  src/features/dashboard/container/progress-overview.tsx
  src/features/dashboard/container/recent-submissions.tsx
  src/features/dashboard/progress-overview.tsx
  src/features/dashboard/recent-submissions.tsx
  src/features/dashboard/user-greeting.tsx
  src/lib/auth.ts
  src/types/utils.ts
Labels: feature ✨, frontend :globe_with_meridians:, backend :zap:

#151 #150 進捗状況の管理を修正 解答済みの表示
  src/app/api/[[...route]]/courses/getCourse.ts
  src/app/students/courses/[courseId]/page.tsx
  src/features/courses/[courseId]/components/card-content.tsx
Labels: bug 🐛, feature ✨, high priority :fire:, frontend :globe_with_meridians:

#155 Fix🐛: ユーザーIDをクエリに追加し、セッションから取得するように修正
  src/app/api/[[...route]]/dashboard/activityHeatmap.ts
  src/app/manage/courses/[courseId]/new/page.tsx
  src/app/manage/page.tsx
  src/app/profile/page.tsx
  src/app/students/courses/[courseId]/[problemId]/[submissionId]/page.tsx
  src/app/students/courses/[courseId]/[problemId]/challenge/page.tsx
  src/app/students/courses/[courseId]/[problemId]/page.tsx
  src/app/students/courses/[courseId]/page.tsx
  src/app/students/courses/page.tsx
  src/components/ui/breadcrumb.tsx
  src/components/ui/carousel.tsx
  src/features/dashboard/container/activity-heatmap.tsx
  src/features/dashboard/container/progress-overview.tsx
  src/features/dashboard/container/recent-submissions.tsx
Labels: feature ✨, frontend :globe_with_meridians:, backend :zap:
